version: "3.8"

services:
  bank-db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: bank
    volumes:
      - postgres1:/data/postgres
      - ./bank-module/database/bank.sql:/docker-entrypoint-initdb.d/bank.sql

  sso-db:
    image: postgres:14.5
    ports:
      - "5488:5432"
    environment:
      POSTGRES_USER: ssotest
      POSTGRES_PASSWORD: ssotest1234
      POSTGRES_DB: sso
    volumes:
      - postgres2:/data/postgres
      - ./bank-module/database/sso.sql:/docker-entrypoint-initdb.d/sso.sql
  application:
    build: target/docker/stage
    image: docker.io/library/tiny-bank-application:latest
    environment:
      DB_URL: db
      DB_NAME: bank
      DB_PASS: test1234
      DB_USER: test
    ports:
      - "8080:8080"
    depends_on:
      - bank-db
volumes:
  postgres1:
  postgres2: