version: "3.8"

services:
  bank-db:
    image: postgres:14.5
    container_name: bank-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: bank
    volumes:
      - postgres1:/data/postgres
      - ./src/main/resources/bank.sql:/docker-entrypoint-initdb.d/init.sql

  sso-db:
    image: postgres:14.5
    container_name: sso-db
    ports:
      - "5488:5432"
    environment:
      POSTGRES_USER: ssotest
      POSTGRES_PASSWORD: ssotest1234
      POSTGRES_DB: sso
    volumes:
      - postgres2:/data/postgres
      - ./src/main/resources/bank.sql:/docker-entrypoint-initdb.d/init.sql

  application:
    image: docker.io/library/tiny-bank:1.0
    network_mode: "host"
    ports:
      - "1234:1234"
    depends_on:
      - bank-db
      - sso-db
volumes:
  postgres1:
  postgres2: